export const GET_ALL_CHARS = 'GET_ALL_CHARS';
export const LOADING_ALL_CHARS = 'LOADING_ALL_CHARS';
export const GET_RANDOM_CHAR = 'GET_RANDOM_CHAR';
export const LOADING_RANDOM_CHAR = 'LOADING_RANDOM_CHAR';
export const RANDOM_CHAR_ERROR = 'RANDOM_CHAR_ERROR';
